### PR TITLE
Install the correct python version up front in CI

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR addresses an issue in the CI where the desired python version is completely ignored and all jobs use the latest version.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
This now exposes the failure we saw in the conda testing.

@alurban, please merge this even with the failing CI, which should be addressed in #121 and #123.

**Comment by alurban** [comment]
@duncanmmacleod, should #124 be merged first? Do you expect that merging this one will fix the other two?

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod, should #124 be merged first? Do you expect that merging this one will fix the other two?

#124 is _this_ ticket, so yes, this should be merged first. It will not fix anything, but will mean that the CI we are running in those PRs is actually doing what it says it is.

**Comment by alurban** [comment]
> #124 is _this_ ticket

I knew that, I just wanted to see if PRs could recursively link to themselves

> so yes, this should be merged first. It will not fix anything, but will mean that the CI we are running in those PRs is actually doing what it says it is.

It looks like you've already taken care of merging, thanks for that

**Pull request merged**
